services:
  - type: web
    name: django-black-dashboard
    plan: starter
    env: python
    #region: frankfurt  # region should be same as your database region.
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi:application"
    
