# Generated by Django 4.2.9 on 2024-03-14 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('team', models.CharField(max_length=64)),
                ('Pos', models.CharField(max_length=2)),
                ('Rank', models.PositiveIntegerField()),
                ('PPI', models.FloatField()),
                ('MP', models.PositiveIntegerField()),
                ('G', models.PositiveIntegerField()),
                ('SOnT', models.PositiveIntegerField()),
                ('SOffT', models.PositiveIntegerField()),
                ('BS', models.PositiveIntegerField()),
                ('OG', models.PositiveIntegerField()),
                ('A', models.PositiveIntegerField()),
                ('P', models.PositiveIntegerField()),
                ('C', models.PositiveIntegerField()),
                ('Tk', models.PositiveIntegerField()),
                ('INT', models.PositiveIntegerField()),
                ('FW', models.PositiveIntegerField()),
                ('FC', models.PositiveIntegerField()),
                ('O', models.PositiveIntegerField()),
                ('YC', models.PositiveIntegerField()),
                ('RC', models.PositiveIntegerField()),
                ('GC', models.PositiveIntegerField()),
                ('PW', models.PositiveIntegerField()),
                ('SAV', models.PositiveIntegerField()),
                ('Ca', models.PositiveIntegerField()),
                ('KS', models.PositiveIntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.player')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.team')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_team', to='home.team')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_team', to='home.team')),
            ],
        ),
    ]
