# Generated by Django 3.2.25 on 2024-04-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_game_played'),
    ]

    operations = [
        migrations.CreateModel(
            name='Updated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('updated', models.BooleanField(default=False)),
                ('last_excel_read', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
