# Generated by Django 3.2.25 on 2024-04-16 17:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updated',
            name='updated',
        ),
        migrations.AlterField(
            model_name='updated',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
