# Generated by Django 3.2.25 on 2024-04-17 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20240416_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_team_future', to='home.team')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_team_future', to='home.team')),
            ],
        ),
    ]
